version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: mkdir -p ./test-results && ls -ltr
          name: create test dir
      - run:
          command:  python -m pytest --junitxml=./test-results/junit.xml trapping_rain_water.py
          name: Test
      - store_test_results:
          path: ./test-results

workflows:
  main:
    jobs:
      - build-and-test
